### ISSUE TITLE
The code should be improved to be more readable and efficient.

### ISSUE THREAD

**Issue by NekoSakuraLucia** [midnightdoggo19/discord-bsky#1]
## Issue with the Main File `index.js`

In the `index.js` file, there are areas where the code can be improved to enhance both performance and readability. Some of the main issues might include:

1. **Cluttered Code**:
   Code that is long or not well-organized can make maintenance difficult. Using smaller, modular functions and breaking down the code into manageable pieces can make it easier to read and maintain.

2. **Inefficiency**:
   Code that performs redundant tasks or does not use resources efficiently may slow down the program. For example, repetitive calculations or unnecessary data access can be optimized.

3. **Lack of Clear Formatting**:
   Code that lacks consistent formatting, such as unclear function and variable names, can make it harder for others (or yourself in the future) to read and understand. It's important to use meaningful names and maintain a clear structure.

## Suggested Improvements

- **Break Code into Smaller Functions**: This will make complex code easier to understand and maintain.
- **Use Code Formatting Tools**: Tools like Prettier or ESLint can help reduce clutter and maintain consistent formatting.
- **Add Comments**: Explain complex or important sections of code so that others (or yourself later) can understand them more easily.

Improving the readability and efficiency of the code will help with maintenance and allow the team to collaborate more effectively.

**Comment by NekoSakuraLucia** [comment]
This is just a suggestion. If you'd like, you can assign this task to me, and I'd be happy to take care of it for you.

**Comment by midnightdoggo19** [comment]
If that's something you feel like doing then go ahead. Thanks!

**Comment by NekoSakuraLucia** [comment]
> If that's something you feel like doing then go ahead. Thanks!

Okay!
